### ISSUE TITLE
Invalid Json sent to Github

### ISSUE THREAD

**Issue by joriscode** [padurean/vistablog#5]
I have a single markdown file with `Hello World` inside along a very simple `header.html` and `footer.html`.

I run the command `sbt run <blog-path>` (terminates successfully) but the target file contains 
`{"message":"Problems parsing JSON","documentation_url":"https://developer.github.com/v3"}` instead of `Hello World`. The header and the footer are correctly added to the target file.

According to https://developer.github.com/v3/#client-errors this problem is due to an invalid Json format.

**Comment by padurean** [comment]
Hi, @joriscode.

I was not able to reproduce the problem.
Here's what i did:

``` bash
~/workspace/scalatic (master) λ   cp -R src/test/scala/scalatictest/ ~/tmp/vvv/
~/workspace/scalatic (master) λ   rm -Rf ~/tmp/vvv/expected/
~/workspace/scalatic (master) λ   sbt "run /Users/myusername/tmp/vvv"
~/workspace/scalatic (master) λ   open ~/tmp/vvv/target/index.html
```

Everything worked fine - the sample blog has shown as expected.

**Comment by joriscode** [comment]
Hi @padurean!

Thank you for your quick answer!
Indeed, it works. I found the problem: after the first compilation the `new/files` where moved to `source/posts`. I would suggest to check if there are any files in `new/` before requesting the conversion on Github.

Btw, it would be easy to extrapolate `~/relativePath` to `System.getProperty("user.home")` + `relativePath`.
