### ISSUE TITLE
why the embedded youtube video can't be displayed?

### ISSUE THREAD

**Issue by luckypoem** [padurean/vistablog#7]
hi.

i installed ur app: http://slt.bright.biz.st ,but the embedded youtube video in this article:
http://slt.bright.biz.st/因为我爱你-2016-11-13-10-07.html can't be displayed?why?
thanks

**Comment by padurean** [comment]
Hi.

I am sorry, but i can not see any youtube url in the page source for that blog post.
It probably needs to be tackled at markdown level - i.e. the markdown based on which that post was generated.
For example, first thing i'd check would be if the link is specified correctly, using a correct markdown syntax.
I will try to reproduce it myself, but i can not do that right now, maybe in few hours.
